### PR TITLE
overlay-files: Refactor wlan0 ifup Networking Configuration

### PR DESCRIPTION
**Pull request by gtxaspec**
- Incorporated a 15-second timeout within udhcpc_opts, ensuring adequate time for the device to aquire a dhcp lease from the network before forking to the background.
- Transitioned all wpa_supplicant parameters to the `pre-up` directive, ensuring wpa_supplicant initialization precedes DHCP client execution.

Collectively, these modifications optimize the DHCP lease acquisition process, enhancing the device's network initialization speed.

### CODE REVIEW

**Comment by themactep** [comment]
wext was neede for some mt7601 modules. We need to make sure those are not left out with this pr.

**Comment by gtxaspec** [comment]
@themactep thanks for the insight, the wext driver has been restored.

**Review by ZigFisher — COMMENTED** [review]
Good job, thank you

Please pay attention to these DHCP client options. Perhaps your option should be moved here, so as not to clutter the configuration file.

https://github.com/OpenIPC/firmware/blob/a5ec76b3386d70008540ddfc8c1006fd7c2806a5/general/package/busybox/busybox.config#L998

**Review by FlyRouter — APPROVED** [review]

**Comment by gtxaspec** [comment]
@FlyRouter I integrated the changes you suggested, modifying the busybox.config and cleaning the config files.

Thank You!

**Review by FlyRouter — APPROVED** [review]
Thank you !

**Pull request merged**
