### PR TITLE
Add RTL8812EU driver & wifibroadcast script support for FPV firmware

### PR DESCRIPTION
**Pull request by libc0607**
See https://github.com/OpenIPC/firmware/issues/1344. 

The driver has been tested in Chinese communities these days, on SSC338Q (MC800s), SSC30KQ (MC-L12), and Hi3516EV200.
- [x] The MCS rates work correctly
- [x] TX power can be set by ```driver_txpower_override``` in ```/etc/wfb.conf``` (same as RTL8812AU-based adaptors) 
- [x] TX power can be dynamically set by ```iw set txpower fixed``` 
- [x] ```iw reg set``` works (phy won't say it's self-managed) 

It's disabled by default. I will write a tutorial for the wiki repo later.

### CODE REVIEW

**Comment by libc0607** [comment]
I've written a draft about the usage 
See https://github.com/libc0607/openipc-wiki/blob/master/en/fpv-bl-m8812eu2-wifi-adaptors.md

**Comment by FlyRouter** [comment]
> I've written a draft about the usage See https://github.com/libc0607/openipc-wiki/blob/master/en/fpv-bl-m8812eu2-wifi-adaptors.md

Excellent documentation, you can send a PR to Wiki and it will be accepted.

**Comment by ETE-Design** [comment]
Still would really like is someone could make a Windows Driver for it to recieve WifiBroadcasting from OpenIPC on Windows

**Comment by widgetii** [comment]
@libc0607 can please you resolve conflicts in `general/package/Config.in`?

**Comment by libc0607** [comment]
> @libc0607 can please you resolve conflicts in `general/package/Config.in`?

Just made a quick fix on github web

**Comment by widgetii** [comment]
Merged, Thank you for your great work!

**Pull request merged**
