### PR TITLE
[no ci] overlay-files: add ingenic-pwm package

### PR DESCRIPTION
**Pull request by gtxaspec**
Adding "ingenic-pwm" userspace utility to allow the user to control PWM channels.  Some devices control LEDs, etc using PWM channels, and there is currently no way to control them from userspace.

This package depends on the HAL driver changes in https://github.com/OpenIPC/openingenic/pull/21

```
root@openipc-t31:~# ingenic-pwm 
INGENIC PWM Control Version: Oct 18 2023_19:08:45_latest-2286-gbc30a711
Usage: ingenic-pwm [options]

Options:
  -c, --channel=<0-7>            Specify PWM channel number
  -q, --query                    Query channel state
  -e, --enable                   Enable channel
  -d, --disable                  Disable channel
  -p, --polarity=<0|1>           Set polarity (0: Inversed, 1: Normal)
  -D, --duty=<duty_ns>           Set duty cycle in ns
  -P, --period=<period_ns>       Set period in ns
  -u, --ramp_up                  Ramp up PWM
  -w, --ramp_down                Ramp down PWM
  -i, --increment=<value>        Set increment for ramp up
  -m, --decrement=<value>        Set decrement for ramp down
  -x, --max_duty=<max_duty_ns>   Set max duty for ramping
  -n, --min_duty=<min_duty_ns>   Set min duty for ramping
  -h, --help                     Display this help message
```

### CODE REVIEW

**Review by FlyRouter — APPROVED** [review]
Thank you

**Comment by themactep** [comment]
Just an idea
```
  -u, --ramp_up                  Ramp up PWM
  -w, --ramp_down                Ramp down PWM
  -i, --increment=<value>        Set increment for ramp up
  -m, --decrement=<value>        Set decrement for ramp down
```
could be squished into
```
-r, --ramp=<value>
```
where value is either +int or -int defining both direction and amount.

**Comment by gtxaspec** [comment]
great idea @themactep, its been implemented! thank you

**Comment by gtxaspec** [comment]
example command to ramp LED up from dark to brightest:
```
ingenic-pwm -c 2 -P 1000000 -x 1000000 -n 0 -r 10000
Period = 1000000
Max Duty = 1000000
Min Duty = 0
Ramp Rate = 10000
```
change `-r` to `-10000` to dim

**Comment by themactep** [comment]
Does anyone really count in nanoseconds? Change it to human units (seconds) and convert to computer ones internally.

**Pull request merged**
