### PR TITLE
Package: add global variable to request git sha

### PR DESCRIPTION
**Pull request by viktorxda**

### CODE REVIEW

**Review by FlyRouter — CHANGES_REQUESTED** [review]
I think there is a problem because the method of getting the source code is not specified, in our case it should be "git".

**Review by FlyRouter — COMMENTED** [review]
We need to get the sources through GIT, because only there are blanks and labels we need in some cases, as well as you can track the latest version.
We experimented for a long time and settled on the current version.

**Comment by viktorxda** [comment]
The same technique is already being used by the kernel, tarballs are downloaded by wget, which is the default setting.

**Review by FlyRouter — APPROVED** [review]
Thank you

**Pull request merged**
