### PR TITLE
WIP: Support Ingenic T31 GLIBC toolchain

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Review by FlyRouter — COMMENTED** [review]
Perhaps we should think of some more beautiful structure for this particular case. 
We can consider any proposals.

**Comment by ajlennon** [comment]
Hi @FlyRouter @viktorxda could you please kick off a toolchain workflow to test creation of the T31 GLIB toolchain? Thanks!

**Review by FlyRouter — APPROVED** [review]
Thank you.
I don’t quite agree with the name of the profile and the structure at this moment, but I hope we can work on it some more.

**Comment by ajlennon** [comment]
Thanks. One thought I had was to break out the naming to include the code library such as $platform_$library_$distro_defconfig 🤷‍♀️

**Pull request merged**
