### PR TITLE
ingenic-osdrv-t31: Improve image quality by replacing gc2053-t31.bin sensor param file from stock fw

### PR DESCRIPTION
**Pull request by gtxaspec**
Update `gc2053-t31.bin` with sensor param file from stock FW.  The result is Improved image quality: better contrast, saturation and luminance.

### CODE REVIEW

**Review by ZigFisher — COMMENTED** [review]
Thank you.
This patch will require additional testing as devices with this sensor are already in use and we need to make sure that nothing will be broken.

**Comment by gtxaspec** [comment]
@ZigFisher Thank You!

If anyone else would be able to test on their devices, the feedback would be appreciated.  I tested on: 

Wyze V3
Wyze Doorbell
AtomCam 2

**Comment by viktorxda** [comment]
Just from very quick test on a Wyze V3, the image quality is indeed improved.
I assume this is only a image parameter calibration file, something similar is used for Sigmastar as well.

**Comment by ZigFisher** [comment]
Test passed, thank you all

**Pull request merged**
