### PR TITLE
Update load_grainmedia to work on GM8135 SOC. 

### PR DESCRIPTION
**Pull request by willersonsp**
This pull request needs another repository pull request to be approved first.

https://github.com/OpenIPC/linux/pull/22

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
I have no objections, but I am somewhat confused in your work GM8136 by the presence of modified FPV files.
Can you give an explanation?

**Comment by flyrouter** [comment]
> This pull request needs another repository pull request to be approved first.
> 
> [OpenIPC/linux#22](https://github.com/OpenIPC/linux/pull/22)

Done

**Comment by willersonsp** [comment]
> I have no objections, but I am somewhat confused in your work GM8136 by the presence of modified FPV files. Can you give an explanation?

probably it was some bug on the merging proccess, when i commited on my branch i forgot to pull the changes on my branch first, then it got merged and added these files, if you need another pull request with only my changes, just tell me and i can do without any problem.

**Review by flyrouter — APPROVED** [review]
Thank you

**Pull request merged**
