### PR TITLE
[no ci] ingenic-osdrv-t20: use sinfo module from openingenic for T20 support

### PR DESCRIPTION
**Pull request by gtxaspec**
Implement Wyze T20 device support to OpenIPC:

Switch to using `sinfo.ko` from the openingenic package, as it supports a wider range of sensors than the pre-compiled versions included in the `ingenic-osdrv-t20` package.  

Modify `load_ingenic`  T20 script to match the behavior of the T31 and T40 scripts, using `modprobe`.

### CODE REVIEW

**Review by FlyRouter — APPROVED** [review]
Thank you

**Comment by cronyx** [comment]
Don't forget to enable **BR2_PACKAGE_INGENIC_OPENSDK=y** in t20 profiles

**Comment by gtxaspec** [comment]
@cronyx done =D

**Comment by cronyx** [comment]
> @cronyx done =D

and t20_ultimate_defconfig too ;)

**Comment by gtxaspec** [comment]
already enabled for ultimate
https://github.com/OpenIPC/firmware/blob/551a0c70c37f6729dd7a4caecf8d2f0f5325c88f/br-ext-chip-ingenic/configs/t20_ultimate_defconfig#L63

**Pull request merged**
