### PR TITLE
Add RTL8189ES to t20_ultimate_defconfig

### PR DESCRIPTION
**Pull request by moosehadley**
Add RTL8189ES to t20_ultimate_defconfig to support wifi on Wyze Cam Pan v1

### CODE REVIEW

**Review by FlyRouter — APPROVED** [review]
Thank you

**Comment by FlyRouter** [comment]
Please remember to add your profile to /etc/wireless/* afterwards.

**Comment by gtxaspec** [comment]
https://github.com/OpenIPC/firmware/blob/8b5d88254aa3ce6229c6c4197996f17f3a179e93/general/overlay/etc/wireless/sdio#L78

should be changed to:
`if [ "$1" = "rtl8189es-t20-wyze-pan-v1" ]; then`

Since then PanV1 does not use an 8189**FTV** chipset, just to prevent confusion.

@moosehadley I can submit a PR, or you can adjust it if you like.

**Comment by gtxaspec** [comment]
fixed wireless name for pan v1 in https://github.com/OpenIPC/firmware/pull/1084

**Pull request merged**
