### PR TITLE
Update onvif-simple-server.mk

### PR DESCRIPTION
**Pull request by Gdaadg**
update onvif-simple-server.mk

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
Thank you
Have you checked it, is it working completely?

**Comment by Gdaadg** [comment]
Да. Работает сейчас у меня на камере. 17.08.2024, 23:59, "Signor Pellegrino" ***@***.***>***@***.*** commented on this pull request.Have you checked it, is it working completely?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Gdaadg** [comment]
Да. Работает сейчас у меня на камере.

  
>Суббота, 17 августа 2024, 23:59 +03:00 от Signor Pellegrino ***@***.***>:
> 
> 
>@flyrouter commented on this pull request.
>Have you checked it, is it working completely?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <OpenIPC/firmware/pull/1524/review/2244150838 @ github . com> 
 
 
--
Д Г

**Comment by flyrouter** [comment]
Thank you
In a few hours I will make some small edits and merge
I will have some suggestions, is there a possibility to discuss this in Telegram messenger?

**Comment by Gdaadg** [comment]
> Thank you In a few hours I will make some small edits and merge I will have some suggestions, is there a possibility to discuss this in Telegram messenger?

OK

**Comment by Gdaadg** [comment]
Может я не так всё сделал? Как можно объединить два Commits 
1. https://github.com/OpenIPC/firmware/pull/1524 #1524 
2. https://github.com/OpenIPC/firmware/pull/1523 
#1523
в один. Или нужно их удалить и сделать все заново?
Я с github только начал разбираться.

**Comment by flyrouter** [comment]
In the future, if there are dependencies, please try to combine them.

As for the third patch, we need to work on it.
Please contact me in Telegram if there is an opportunity for a quicker dialogue.
The main point is that we need to use the motors repository and make a subset of configurations, then everything will fall into place. Using each package separately for many configurations will unfortunately quickly clutter our file system and package structure.

**Pull request merged**
