### PR TITLE
wireless-scripts: add support for ingenic t31 with rtl8189fs-openipc

### PR DESCRIPTION
**Pull request by gtxaspec**
Add support for Wyze V3 / AtomCam 2 / Wyze Doorbell to the /etc/wireless/sdio script, and enable driver via adding `BR2_PACKAGE_RTL8189FS_OPENIPC=y` to the `t31_ultimate_defconfig` Tested on Wyze V3 (RTL8189FTV), AtomCam 2, Wyze Doorbell (RTL8189FTV)

### CODE REVIEW

**Comment by gtxaspec** [comment]
pre-compiled 8189fs.ko for testing
[8189fs.ko.zip](https://github.com/OpenIPC/firmware/files/12391659/8189fs.ko.zip)

**Comment by viktorxda** [comment]
Seems to work, tested on a Wyze V3 with RTL8189 (V2.02_20210523).

One suggestion would be to short the commands, to remove some of the redundancy:
```
set_mmc() {
	mmc=/sys/devices/platform/jzmmc_v1.2.$1/present
	if [ "$(cat $mmc)" = "N" ]; then
		echo "INSERT" > $mmc
	fi
}

# T31 Wyze V3 RTL8189FTV
if [ "$1" = "rtl8189ftv-t31-wyze-v3" ]; then
	set_mmc 1
	modprobe 8189fs
	exit 0
fi
```

**Comment by ZigFisher** [comment]
I see that this PR is in draft mode. 
Please let me know when it is complete, thanks.

**Comment by gtxaspec** [comment]
ready @ZigFisher =D

**Review by ZigFisher — APPROVED** [review]

**Pull request merged**
