### PR TITLE
[General] replace external chipset directories with general packages

### PR DESCRIPTION
**Pull request by viktorxda**
This commit expands on the idea from #763
The approach might be too radical and is more intended for consultation and testing.

Changes are:
- convert /general into a external buildroot directory
- remove the symlinks to /general from each chipset vendor
- migrate the separate chipset vendor externals to /general
- replace hardcoded package paths
- consolidate the different linux patcher
- rename duplicate variable names

The overall goal is to remove as much redundancy as possible without breaking anything.

Edit:
- [[current *hisilicon]](https://github.com/OpenIPC/firmware/tree/master/br-ext-chip-hisilicon) -> [[changed *hisilicon]](https://github.com/viktorxda/firmware/tree/master/br-ext-chip-hisilicon)
- [[current /general]](https://github.com/OpenIPC/firmware/tree/master/general) -> [[changed /general]](https://github.com/viktorxda/firmware/tree/master/general)

### CODE REVIEW

**Comment by themactep** [comment]
If it builds with no conflicts, let's merge it. Otherwise, we'll ether have to postpone all further changes until it's finished, or you will have to fix conflicts emerging after any accepted PR before this one :)

**Comment by themactep** [comment]
Godspeed :)
Great job, @viktorxda!

**Comment by themactep** [comment]
Seems legit.
```
$ ls -l op*.tgz | ls -l $(awk '{print $11}') | awk '{print $9,$5}'
openipc.fh8852v100-nor-lite.tgz-202305061003 5932266
openipc.fh8852v200-nor-lite.tgz-202305061012 6350902
openipc.gk7102-nor-lite.tgz-202305061003 5568552
openipc.gk7102s-nor-lite.tgz-202305061003 5558873
openipc.gk7202v300-nor-lite.tgz-202305061012 7160981
openipc.gk7205v200-nor-fpv.tgz-202305061013 6948387
openipc.gk7205v200-nor-lite.tgz-202305061021 7136307
openipc.gk7205v200-nor-lte.tgz-202305061017 6905274
openipc.gk7205v200-nor-ultimate.tgz-202305061016 8032871
openipc.gk7205v210-nor-lite.tgz-202305061021 7136609
openipc.gk7205v300-nor-fpv.tgz-202305061014 6948514
openipc.gk7205v300-nor-lite.tgz-202305061015 7148750
openipc.gk7205v300-nor-lte.tgz-202305061017 6905617
openipc.gk7205v300-nor-ultimate.tgz-202305061022 8045796
openipc.gk7605v100-nor-lite.tgz-202305061021 7136691
openipc.gm8136-nor-lite.tgz-202305061025 6535349
openipc.hi3516av100-nand-ultimate.tgz-202305061028 17807722
openipc.hi3516av100-nor-lite.tgz-202305061025 6233755
openipc.hi3516av100-nor-ultimate.tgz-202305061028 7719478
openipc.hi3516av200-nand-ultimate.tgz-202305061032 18409573
openipc.hi3516av200-nor-lite.tgz-202305061028 6506343
openipc.hi3516av200-nor-ultimate.tgz-202305061032 7989779
openipc.hi3516av300-nor-lite.tgz-202305061033 10326264
openipc.hi3516cv100-nor-lite.tgz-202305061031 6628267
openipc.hi3516cv200-nor-lite.tgz-202305061034 7150961
openipc.hi3516cv300-nand-ultimate.tgz-202305061041 20097911
openipc.hi3516cv300-nor-lite.tgz-202305061036 6728848
openipc.hi3516cv300-nor-mini.tgz-202305061037 6448548
openipc.hi3516cv300-nor-ultimate.tgz-202305061041 8221553
openipc.hi3516cv500-nor-lite.tgz-202305061047 10336476
openipc.hi3516dv100-nand-ultimate.tgz-202305061043 17882253
openipc.hi3516dv100-nor-lite.tgz-202305061039 6864042
openipc.hi3516dv100-nor-ultimate.tgz-202305061043 7750897
openipc.hi3516dv200-nor-lite.tgz-202305061044 6711640
openipc.hi3516dv300-nor-lite.tgz-202305061047 10325767
openipc.hi3516ev100-nor-lite.tgz-202305061045 6704015
openipc.hi3516ev200-nand-ultimate.tgz-202305061051 18810621
openipc.hi3516ev200-nor-fpv.tgz-202305061045 7047175
openipc.hi3516ev200-nor-lite.tgz-202305061050 6711639
openipc.hi3516ev200-nor-lte.tgz-202305061054 7007974
openipc.hi3516ev200-nor-ultimate.tgz-202305061051 8195476
openipc.hi3516ev300-nand-ultimate.tgz-202305061107 19912462
openipc.hi3516ev300-nor-fpv.tgz-202305061324 7047317
openipc.hi3516ev300-nor-lite.tgz-202305061058 6723678
openipc.hi3516ev300-nor-lte.tgz-202305061052 7008096
openipc.hi3516ev300-nor-ultimate.tgz-202305061107 8580816
openipc.hi3518cv100-nor-lite.tgz-202305061101 6628314
openipc.hi3518ev100-nor-lite.tgz-202305061103 6689807
openipc.hi3518ev200-nand-ultimate.tgz-202305061105 20431385
openipc.hi3518ev200-nor-lite.tgz-202305061057 7220883
openipc.hi3518ev200-nor-mini.tgz-202305061058 6940139
openipc.hi3518ev200-nor-ultimate.tgz-202305061105 8447669
openipc.hi3518ev300-nand-ultimate.tgz-202305061108 21229151
openipc.hi3518ev300-nor-lite.tgz-202305061100 7219175
openipc.hi3518ev300-nor-ultimate.tgz-202305061108 9041227
openipc.hi3519v101-nor-lite.tgz-202305061105 7266367
openipc.hi3536cv100-nor-lite.tgz-202305061107 5405673
openipc.hi3536dv100-nor-lite.tgz-202305061104 5749478
openipc.nt98562-nor-lite.tgz-202305061114 6805369
openipc.nt98566-nor-lite.tgz-202305061113 6804663
openipc.rv1109-nand-lite.tgz-202305061121 12101233
openipc.rv1126-nand-lite.tgz-202305061119 12099176
openipc.ssc335de-nor-lite.tgz-202305061126 7171254
openipc.ssc335-nor-lite.tgz-202305061124 7174422
openipc.ssc337de-nor-lite.tgz-202305061127 7171268
openipc.ssc337-nor-lite.tgz-202305061122 7174806
openipc.ssc338q-nand-lite.tgz-202305061133 19757213
openipc.ssc338q-nor-lite.tgz-202305061133 8791519
openipc.t10-nor-lite.tgz-202305061125 6723820
openipc.t20-nor-lite.tgz-202305061130 6307971
openipc.t21-nor-lite.tgz-202305061132 6589330
openipc.t30-nor-lite.tgz-202305061129 6695140
openipc.t31-nor-lite.tgz-202305061136 6994118
openipc.t31-nor-ultimate.tgz-202305061133 7709586
openipc.t40-nor-lite.tgz-202305061136 6427983
openipc.t40-nor-ultimate.tgz-202305061139 7059018
openipc.xm510-nor-lite.tgz-202305061138 4176109
openipc.xm530-nor-lite.tgz-202305061131 5252454
openipc.xm550-nor-lite.tgz-202305061146 5252335
```

**Comment by cronyx** [comment]
> There is an issue when it reaches majestic:
> 
> ```
> >>> majestic master Building
> PATH="/home/runner/work/firmware/firmware/output/per-package/majestic/host/bin:/home/runner/work/firmware/firmware/output/per-package/majestic/host/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"  /usr/bin/make -j3 >/dev/null 2>&1 -C /home/runner/work/firmware/firmware/output/build/majestic-master/
> make[1]: *** [package/pkg-generic.mk:251: /home/runner/work/firmware/firmware/output/build/majestic-master/.stamp_built] Error 2
> make[1]: Leaving directory '/home/runner/work/firmware/firmware/buildroot-2021.02.12'
> make: *** [Makefile:146: all] Error 2
> Error: Process completed with exit code 2.
> ```
`
/usr/bin/make -j3 >/dev/null 2>&1 -C /home/runner/work/firmware/firmware/output/build/majestic-master/`

but package located into

 `/home/runner/work/firmware/firmware/output/build/majestic-current/`

**Pull request merged**
