### PR TITLE
adding atbm-wifi package, atbm6012b-ssc333-tapo-c110 module load

### PR DESCRIPTION
**Pull request by geedubess**
I'm not sure if the github source I'm using for atbm-wifi is the best, but it's the only one I've found.

I'm not sure if the package name is optimal (I copied the source repo name). atbm60xx-v2? atbm60xx-nextgen? etc

I'm not sure if files/ are necessary, so for now they are copied from atbm60xx, but not installed.

I haven't tested atbm60xx (with or without atbm-wifi included), but atbm-wifi **works on my atbm 6012b-x** where atbm60xx does not. I have not tested any of the other atbm-wifi supported models.

Ultimately it probably makes more sense to update the atbm60xx driver, but that's a much bigger problem and requires testing with supported devices that I am not able to do.

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
Thank you

**Comment by flyrouter** [comment]
We are awaiting confirmation from @cronyx

**Comment by niyawe** [comment]
Hi,

i tried building the atbm-wifi package for the atbm6012b and during the Buildstep
```
>>> atbm-wifi HEAD Building
>>> atbm-wifi HEAD Building kernel module(s)
```

i get the following error:
```
/home/niyawe/dl/tapo_c110/builder/openipc/output/build/atbm-wifi-HEAD/./Makefile.build.kernel:10: "============>kernel_version:4.9.84"
scripts/Makefile.lib:402: *** prerequisites cannot be defined in recipes.  Stop.
make[2]: *** [scripts/Makefile.build:544: /home/niyawe/dl/tapo_c110/builder/openipc/output/build/atbm-wifi-HEAD/./hal_apollo] Error 2
make[1]: *** [Makefile:1580: _module_/home/niyawe/dl/tapo_c110/builder/openipc/output/build/atbm-wifi-HEAD/.] Error 2
make: *** [package/pkg-generic.mk:284: /home/niyawe/dl/tapo_c110/builder/openipc/output/build/atbm-wifi-HEAD/.stamp_built] Error 2
make: Leaving directory '/home/niyawe/dl/tapo_c110/builder/openipc/output/buildroot-2024.02.6'
```

**Comment by geedubess** [comment]
@niyawe - Huh. I'm not familiar with this build system yet, but I'm having a hard time seeing how openipc/output/build/linux-custom/scripts/Makefile.lib:402 would come into play there.

"Ubuntu 24.04.1 LTS"
openipc-firmware: HEAD @ (https://github.com/geedubess/openipc-firmware/tree/add-6012b-support)

Can you think of anything I can poke at to try to help debug this? I rm openipc/output before building using openipc-builder. My openipc-builder is currently locally modified, but was not when I pushed my changes to github - just defconfig changes and #rm -rf openipc.

You're not also including/building the atbm60xx driver, right?

```
>>> atbm-wifi HEAD Building                                                                                                                                                              
>>> atbm-wifi HEAD Building kernel module(s)                                                                                                                                             
GIT_DIR=. PATH="/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/bin:/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/sbin:/usr/local/sbi
n:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" PKG_CONFIG="/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/bin/pkg-config
" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_LIBDIR="/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/
lib/pkgconfig:/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/share/pkgconfig" BR_BINARIES_DIR=/home/gws/prj/tapoc110/builder/openipc/output/images KCFLAGS=-Wno
-attribute-alias /usr/bin/make -j13 -C /home/gws/prj/tapoc110/builder/openipc/output/build/linux-custom HOSTCC="/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/
bin/ccache /usr/bin/gcc -O2 -isystem /home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/include -L/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wi
fi/host/lib -Wl,-rpath,/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/lib" ARCH=arm INSTALL_MOD_PATH=/home/gws/prj/tapoc110/builder/openipc/output/per-package/
atbm-wifi/target CROSS_COMPILE="/home/gws/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/bin/arm-openipc-linux-musleabihf-" WERROR=0 REGENERATE_PARSERS=1 DEPMOD=/home/gw
s/prj/tapoc110/builder/openipc/output/per-package/atbm-wifi/host/sbin/depmod INSTALL_MOD_STRIP=1 KSRC=/home/gws/prj/tapoc110/builder/openipc/output/build/linux-custom CONFIG_ATBM6012B_y=n CONFIG_ATBM603x=n CONFIG_ATBM6132=n CONFIG_ATBM6012B_y=y CONFIG_ATBM_USB_BUS=y CONFIG_ATBM_SDIO_BUS=n CONFIG_ATBM_MODULE_NAME="atbm6012b_wifi_usb" PWD=/home/gws/prj/tapoc110/builder/openipc/output/build/atbm-wifi-HEAD/. M=/home/gws/prj/tapoc110/builder/openipc/output/build/atbm-wifi-HEAD/. modules                                                                     
/home/gws/prj/tapoc110/builder/openipc/output/build/atbm-wifi-HEAD/./Makefile.build.kernel:10: "============>kernel_version:4.9.84"                                                        
CC [M]  /home/gws/prj/tapoc110/builder/openipc/output/build/atbm-wifi-HEAD/./hal_apollo/mac80211/main.o
...
```

**Pull request merged**
